# Site settings
baseURL = "https://henryrahmann.netlify.app/"
languageCode = "en-us"
title = "HR"
theme = "forty"


[params]
 
  name = "Henry"
  description = "Your description"

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  [params.navigation]
    logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "About Me"
      url = "blogs"

    [[params.navigation.links]]
      name = "Projects"
      url = "projects"

    [[params.navigation.button1]]
      name = "Get Started"
      url = "blogs"

  [params.banner]
    title = "Hi, I'm Henry"
    subtitle = "Kong Kong | Cape Town | Frankfurt | London"
    buttonText = "Here we go"

  [params.tiles]
    enable = true

    [[params.tiles.showcase]]
      title = "Henry in 3 Paragraphs"
      subtitle = "A little bit about myself"
      image = "henry.jpg"
      url = "blogs/overview"
    
    [[params.tiles.showcase]]
      title = "What's up with the aeroplane logo?"
      subtitle = "My greatest passion"
      image = "airstrip.jpg"
      url = "blogs/aviation"
    
    [[params.tiles.showcase]]
      title = "An example of my latest work"
      subtitle = "Comparative GDP Analysis of Germany, India, United States"
      image = "gdp.svg"
      url = "projects/gdp_data"

    [[params.tiles.showcase]]
      title = "Another example of my latest work"
      subtitle = "Analysis of IMDB Ratings for Spielberg vs Burton"
      image = "movies.jpg"
      url = "projects/imdb_data"


  # Section Type Two
  [params.two]
    enable = true
    title = "Now what?"
    subtitle = """If you find any of what I've done vaguely interesting and would like to see it all again, hit the button below."""
    buttonText = "Get Started"
    url = "blogs"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Go!"
    buttonClear = "Clear"

    [[params.contact.email]]
    title = "Reach out"
    email = "hrahmann.mfa2021@london.edu"

    [[params.contact.address]]
    title = "Address"
    street = "Regents Park"
    city = "London NW1 4SA"
    country = "United Kingdom"

  # Footer section
  [params.footer]
    enable = true
    copyright = "henry's brain"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/in/henry-rahmann-64508858"
      label = "LinkedIn"
